"""empty message

Revision ID: 426d7f94deab
Revises: 14c1a2fe54ec
Create Date: 2026-07-21 15:56:00.111577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '426d7f94deab'
down_revision = '14c1a2fe54ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_db',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Roll_No', sa.Integer(), nullable=True),
    sa.Column('Name', sa.String(length=100), nullable=True),
    sa.Column('Age', sa.Integer(), nullable=True),
    sa.Column('Class', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('Roll_No')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_db')
    # ### end Alembic commands ###
