"""Remove unique constraint from Roll_No

Revision ID: 5f0dd43ddd58
Revises: 426d7f94deab
Create Date: 2026-07-29 23:33:17.664030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f0dd43ddd58'
down_revision = '426d7f94deab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_db', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('Roll_No'))
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_db', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_index(batch_op.f('Roll_No'), ['Roll_No'], unique=True)

    # ### end Alembic commands ###
